os: linux
dist: xenial
services:
  - docker

language: python

python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9-dev'

install:
  # upgrade importlib_metadata due to bug in TravisCI
  # https://travis-ci.community/t/build-error-for-python-3-7-on-two-different-projects/12895
  - 'pip install --upgrade importlib_metadata'
  - 'pip install -e .[dev]'

script:
  - flake8
  - pytest --cov

deploy:
  provider: pypi
  user: __token__
  # Due to a bug, using the environment variable defined in the UI for the password
  # https://github.com/travis-ci/travis.rb/issues/687
  on:
    branch: master
    tags: true
    python: '3.8'
  skip_existing: true
