name: Run tests

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
        exclude:
          # Python 3.6 is not available in GitHub Actions Ubuntu 22.04
          - os: ubuntu-latest
            python-version: '3.6'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: python -m pip install .[dev]
      - name: Linting
        run: "flake8"
      - name: Unit tests
        run: "pytest --cov"

  all-tests:
    # Single step that will succeed iff all test steps succeed. To used for branch protection
    runs-on: ubuntu-latest
    needs: [tests]
    if: always()
    steps:
      - name: Failed tests
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
      - name: Cancelled tests
        if: ${{ contains(needs.*.result, 'cancelled') }}
        run: exit 1
      - name: Skipped tests
        if: ${{ contains(needs.*.result, 'skipped') }}
        run: exit 1
      - name: Successful tests
        if: ${{ !(contains(needs.*.result, 'failure')) && !(contains(needs.*.result, 'cancelled')) && !(contains(needs.*.result, 'skipped')) }}
        run: exit 0
